### ISSUE TITLE
Parse Issue of TensorRT

### ISSUE THREAD

**Issue by ycszen** [TAMU-VITA/FasterSeg#7]
When I use the computation code of the tensorrt in your repo, there is a problem.

When the TensorRT ONNXParser parses the onnx model, the returend value is false. And the TensorRT gives an error: Network must have at leaset one output.

Do you have meet the similar problem? And how to solve it?

**Comment by chenwydj** [comment]
Did you change anything in the provided latency measurement script? i.e. code under `FasterSeg/latency`.

I met this problem before. Usually, I have to go through the error log from the TensorRT to find the reason, it will say which layer the error comes from -- mostly it is because some layers in Pytorch is not supported by TensorRT.

**Comment by ycszen** [comment]
No. I didn't do any change.

What's the version of your TensorRT? Maybe the different versions cause the problems.

**Comment by chenwydj** [comment]
Mine is 5.1.5.

**Comment by ycszen** [comment]
Wired. Mine is also 5.1.5. 

Meanwhile, the versions of PyTorch, CUDA are 1.3 and 10.1.

**Comment by ycszen** [comment]
Did you do some specific change on the "interpolate"?

I find that the TensorRT 5.0 is not supportted the "Resize".

**Comment by chenwydj** [comment]
Could you try Pytorch 1.1.0?
And also my onnx version is 1.5.0

**Comment by chenwydj** [comment]
> Did you do some specific change on the "interpolate"?
> 
> I find that the TensorRT 5.0 is not supportted the "Resize".

Nothing special. TensorRT 5.1 supports the interpolation.

**Comment by ycszen** [comment]
Now I use Pytorch 1.2 and TensorRT 5.1. All is Fine.
Thanks for your kindly reply.
